### ISSUE TITLE
Mongodb driver needs to be upgraded to support mongo 2.6

### ISSUE THREAD

**Issue by clexmond** [emirotin/mongo-pool#1]
We are currently using https://github.com/emirotin/mongodb-migrations which has a dependency on mongo-pool. Unfortunately due to a now outdated dependency on pre-1.4 mongodb driver (https://github.com/emirotin/mongo-pool/blob/develop/package.json#L25) we are unable to run migrations against a 2.6+ version of Mongo due to `Error: key $in must not start with '$'`

**Comment by emirotin** [comment]
Thanks for letting me know. Will try to update in a couple of days.

In the meantime it would be great if you can submit a PR (to mongodb-migrations) with a failing testcase, so that I can verify the fix.

**Comment by emirotin** [comment]
Sorry it took me a bit longer than a couple of days to get to this :(
Updated version submitted, will make a new version of https://github.com/emirotin/mongodb-migrations now so that you can test it.

**Comment by emirotin** [comment]
So I wasn't able to reproduce it actually :\

I've added this migration

```
exports.id = 'test3';

exports.up = function (done) {
  var coll = this.db.collection('test');
  coll.update({ name: { $in: ['loki', 'tobi'] } }, { $set: { ok: 1 } }, { multi: true }, done);
};
```

and it works fine with MongoDB 2.6.7 and mongo-pool2@0.6.0 (the previous version)

Though I will update it anyway.

**Comment by emirotin** [comment]
mongodb-migrations@0.3.0 published to npm

Please give it a try. I'm closing this use, please open another one if you still have issue — ideally with the specific migration code so that I can add it to the tests suite.
